security:
  h2-console-secured: false
  actuator-secured: false
  oauth2:
    client:
      clientId: web-spa
      clientSecret: 123456
      accessTokenUri: https://${vcap.application.uris[0]}/oauth/token
#      accessTokenUri: http://localhost:8080/oauth/token
      grantTypes: client_credentials, implicit, password, refresh_token
      authorities: ROLE_USER, ROLE_ADMIN
      scopes: read, write
      accessTokenValiditySeconds: 3600
#      clientAuthenticationScheme:
    resource:
      resourceName: taco-rest
#      userInfoUri: ${USER_INFO_URI:http://localhost:9200/uaa/user/info}