jwt:
  token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ2ZWludGhyb3VnaCIsImlhdCI6MTU4MzMyMDA1MCwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiIsIkFVVEhfV1JJVEUiXSwiZXhwIjoxNTgzMzI2MDUwfQ.kMp1VA16fkO_kXkVMLNwMwjaeaOrFhYyRvC5MlDW4kwxWfG7PuvSvro90ivP2ckyH_NQeQ00IJdcPfJGRyv9xw
  header: Authorization
  secret: NDU0NTY4amhmc3NkeHp6eGNxdzIlMjFAJTIxQCUyM2ZmNQ==
  # 120min
  expiration: 7200000