eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
#    non-secure-port: 80
#    nonSecurePortEnabled: true
    securePortEnabled: true
    secure-port: 443
    homePageUrl: https://${eureka.instance.hostname}
#    statusPageUrl: https://${eureka.instance.hostname}/actuator/info
#    healthCheckUrl: https://${eureka.instance.hostname}/actuator/health
  client:
    service-url:
      defaultZone: ${vcap.services.veinthrough-eureka.credentials.url}
#      defaultZone: http://localhost:8761/eureka