eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
#    non-secure-port: 80
#    nonSecurePortEnabled: true
    securePortEnabled: true
    secure-port: 443
  client:
    service-url:
      defaultZone: ${vcap.services.veinthrough-eureka.credentials.url}
#      defaultZone: http://localhost:8761/eureka