#logging:
#  level:
#    veinthrough.tacocloud.service: INFO

logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.security.oauth2: DEBUG
    org.springframework.cloud.openfeign: DEBUG