taco:
  page-sizes:
    order: 10
    taco: 10

  message:
    sources:
      order: WEB
    queues:
      order: taco.queue.order
    routing-keys:
      order: taco.routingKey.order
    topics:
      order: taco.topic.order

  discount:
    codes:
      discount-1: 10
      discount-2: 20